# Online Inference

This tutorial shows how to use trained PyTorch, TensorFlow, and ONNX (format) models, written in Python, directly in HPC workloads written in Fortran, C, C++ and Python.

The example simulation here is written in Python for brevity, however, the inference API in SmartRedis is the same (besides extra parameters for compiled langauges) across all clients. 


## Installing the ML backends

In order to use the `Orchestrator` database as an inference engine, the Machine Learning (ML) backends need to be built and supplied to the database at runtime. 

To check which backends are built, a simple helper function is available in SmartSim as shown below.

In [1]:
## Installing the ML backends
from smartsim._core.utils.helpers import installed_redisai_backends
print(installed_redisai_backends())

['tensorflow', 'torch', 'onnxruntime']


As you can see, only the Torch backend is built. In order to use the TensorFlow and ONNX backends as well, they need to be built.

The `smart` command line interface can be used to build the backends using the `smart build` command. The output of `smart build --help` is shown below.


```text
usage: smart [-h] [-v] [--device DEVICE] [--no_pt] [--no_tf] [--onnx] [--torch_dir TORCH_DIR] [--libtensorflow_dir LIBTENSORFLOW_DIR] [--only_python_packages] [--keydb]

optional arguments:
  -h, --help            show this help message and exit
  -v                    Enable verbose build process
  --device DEVICE       Device to build ML runtimes for (cpu || gpu)
  --no_pt               Do not build PyTorch backend
  --no_tf               Do not build TensorFlow backend
  --onnx                Build ONNX backend (off by default)
  --torch_dir TORCH_DIR
                        Path to custom <path>/torch/share/cmake/Torch/ directory (ONLY USE IF NEEDED)
  --libtensorflow_dir LIBTENSORFLOW_DIR
                        Path to custom libtensorflow directory (ONLY USED IF NEEDED)
  --only_python_packages
                        If true, only install the python packages (i.e. skip backend builds)
  --keydb               Build KeyDB instead of Redis
```

We use `smart clean` first to remove the previous build, and then call `smart build` to build the new backend set. For larger teams, CrayLabs will help setup your system so that the backends do not have to be built by each user.

By default, the PyTorch and TensorFlow backends are built. To build all three backends for use on CPU, we issue the following command.

In [2]:
!smart clean && smart build --device cpu --onnx

[SmartSim] INFO Running SmartSim build process...
[SmartSim] INFO Checking requested versions...
[SmartSim] INFO Checking for build tools...
[SmartSim] INFO Building Redis version 7.0.5 from https://github.com/redis/redis.git/
[SmartSim] INFO Redis build complete!

ML Backends Requested
╒════════════╤════════╤══════╕
│ PyTorch    │ 1.11.0 │ True │
│ TensorFlow │ 2.8.0  │ True │
│ ONNX       │ 1.11.0 │ True │
╘════════════╧════════╧══════╛

Building for GPU support: False

[SmartSim] INFO ONNX 1.11.0 installed in Python environment
[SmartSim] INFO TensorFlow 2.8.0 installed in Python environment
[SmartSim] INFO Building RedisAI version 1.2.7 from https://github.com/RedisAI/RedisAI.git/
[SmartSim] INFO ML Backends and RedisAI build complete!
[SmartSim] INFO Tensorflow, Torch, Onnxruntime backend(s) built
[SmartSim] INFO SmartSim build complete!


## Starting the Database for Inference

SmartSim performs online inference by using the SmartRedis clients to call into the
Machine Learning (ML) runtimes linked into the Orchestrator database. The Orchestrator
is the name in SmartSim for a Redis or KeyDB database with a RedisAI module built
into it with the ML runtimes.

Therefore, to perform inference, you must first create an Orchestrator database and
launch it. There are two methods to couple the database to your application in
order to add inference capability to your application.
 - standard (not colocated)
 - colocated
 
`standard` mode launches an optionally clustered (across many compute hosts) database instance
that can be treated as a single storage device for many clients (possibly the many ranks
of an MPI program) where there is a single address space for keys across all hosts.

`colocated` mode launches a orchestrator instance on each compute host used by a,
possibly distributed, application. each instance contains their own address space
for keys. In SmartSim, `Model` instances can be launched with a colocated orchetrator
through `Model.colocate_db_tcp` or `Model.colocate_db_udp`. Colocated `Model`s are used for
highly scalable inference where global aggregations aren't necessary for inference.

The code below launches the `Orchestrator` database using the `standard` deployment
method.

In [3]:
# some helper libraries for the tutorial
import io
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import logging
import numpy as np

# import smartsim and smartredis
from smartredis import Client
from smartsim import Experiment

In [4]:
exp = Experiment("Inference-Tutorial", launcher="local")

In [5]:
db = exp.create_database(port=6780, interface="lo")
exp.start(db)

## Using PyTorch

The Orchestrator supports both [PyTorch](https://pytorch.org/)
models and [TorchScript](https://pytorch.org/docs/stable/jit.html) functions and scripts
in PyTorch.

Below, the code is shown to create, jit-trace (prepare for inference), set,
and call a PyTorch Convolutional Neural Network (CNN) with SmartSim and SmartRedis

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout(0.25)
        self.dropout2 = nn.Dropout(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output


To set a PyTorch model, we create a function to "jit-trace" the model
and save it to a buffer in memory.

If you aren't familiar with the concept of tracing, take a look at the
Torch documentation for [trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html#torch.jit.trace)


In [7]:
# Initialize an instance of our CNN model
n = Net()
n.eval()

# prepare a sample input to trace on (random noise is fine)
example_forward_input = torch.rand(1, 1, 28, 28)

def create_torch_model(torch_module, example_forward_input):

    # perform the trace of the nn.Module.forward() method
    module = torch.jit.trace(torch_module, example_forward_input)

    # save the traced module to a buffer
    model_buffer = io.BytesIO()
    torch.jit.save(module, model_buffer)
    return model_buffer.getvalue()

traced_cnn = create_torch_model(n, example_forward_input)

Lastly, we use the SmartRedis Python client to

1. Connect to the database
2. Put a batch of 20 tensors into the database  (``put_tensor``)
3. Set the Torch model in the database (``set_model``)
4. Run the model on the batch of tensors (``run_model``)
5. Retrieve the result (``get_tensor``)


In [8]:
client = Client(address=db.get_address()[0], cluster=False)

client.put_tensor("input", torch.rand(20, 1, 28, 28).numpy())

# put the PyTorch CNN in the database in GPU memory
client.set_model("cnn", traced_cnn, "TORCH", device="CPU")

# execute the model, supports a variable number of inputs and outputs
client.run_model("cnn", inputs=["input"], outputs=["output"])

# get the output
output = client.get_tensor("output")
print(f"Prediction: {output}")


SmartRedis Library@14-11-03:WARNING: Environment variable SR_LOG_FILE is not set. Defaulting to stdout
Prediction: [[-2.2562506 -2.2950497 -2.3529804 -2.2746763 -2.3059285 -2.320581
  -2.3129795 -2.2921813 -2.2667074 -2.3534772]
 [-2.2778108 -2.2807806 -2.3440359 -2.2767324 -2.2972894 -2.3190188
  -2.3278549 -2.2990303 -2.2504287 -2.357964 ]
 [-2.2509592 -2.2798455 -2.352317  -2.2709332 -2.2944198 -2.3347063
  -2.31502   -2.295071  -2.2750957 -2.3636808]
 [-2.2574742 -2.3119466 -2.341312  -2.2681162 -2.2946122 -2.3242433
  -2.3163285 -2.291332  -2.2670102 -2.3584895]
 [-2.2486675 -2.2828228 -2.364878  -2.2737098 -2.2939532 -2.3366425
  -2.310018  -2.3005655 -2.2670708 -2.354104 ]
 [-2.250141  -2.2770994 -2.347671  -2.285967  -2.2989845 -2.328689
  -2.326967  -2.2856352 -2.2700524 -2.360473 ]
 [-2.252362  -2.280783  -2.3437886 -2.2762692 -2.2992115 -2.3580222
  -2.2964714 -2.294584  -2.2730415 -2.3575144]
 [-2.245837  -2.291739  -2.3584027 -2.2776399 -2.3066337 -2.3340435
  -2.311736  -

As we gave the CNN random noise, the predictions reflect that.

If running on CPU, be sure to change the argument in the ``set_model`` call
above to ``CPU``.

## Using TorchScript

In addition to PyTorch models, TorchScript scripts and functions can be set in the
Orchestrator database and called from any of the SmartRedis languages. Functions
can be set in the database in Python prior to application launch and then used
directly in Fortran, C, and C++ simulations.

The example below uses the TorchScript Singular Value Decomposition (SVD) function.
The function set in side the database and then called with a random input
tensor.


In [9]:
def calc_svd(input_tensor):
    # svd function from TorchScript API
    return input_tensor.svd()

In [10]:
# connect a client to the database
client = Client(address=db.get_address()[0], cluster=False)

# test the SVD function
tensor = np.random.randint(0, 100, size=(5, 3, 2)).astype(np.float32)
client.put_tensor("input", tensor)
client.set_function("svd", calc_svd)
client.run_script("svd", "calc_svd", ["input"], ["U", "S", "V"])
U = client.get_tensor("U")
S = client.get_tensor("S")
V = client.get_tensor("V")
print(f"U: {U}\n\n, S: {S}\n\n, V: {V}\n")


U: [[[-0.3603251   0.9078608 ]
  [-0.931906   -0.36054417]
  [-0.04143937  0.21400304]]

 [[-0.5435925   0.24445276]
  [-0.41486043 -0.9098768 ]
  [-0.7296559   0.3352117 ]]

 [[-0.7450588  -0.34492287]
  [-0.5324098  -0.20802858]
  [-0.4017799   0.915288  ]]

 [[-0.7874786  -0.07116459]
  [-0.35922554 -0.75416195]
  [-0.5008337   0.6528212 ]]

 [[-0.36119708 -0.11288617]
  [-0.7034105  -0.61867595]
  [-0.6121685   0.77749395]]]

, S: [[101.74199    6.969097]
 [111.11511   42.052715]
 [144.33199   37.24619 ]
 [145.46298   41.03068 ]
 [130.61479   42.729122]]

, V: [[[-0.694084    0.71989405]
  [-0.71989405 -0.694084  ]]

 [[-0.8110061   0.5850375 ]
  [-0.5850375  -0.8110061 ]]

 [[-0.8134284   0.58166504]
  [-0.58166504 -0.8134284 ]]

 [[-0.7416788   0.6707552 ]
  [-0.6707552  -0.7416788 ]]

 [[-0.80283296  0.596204  ]
  [-0.596204   -0.80283296]]]



In [11]:
## TensorFlow and Keras
import tensorflow as tf
from tensorflow import keras
tf.get_logger().setLevel(logging.ERROR)

# create a simple Fully connected network in Keras
model = keras.Sequential(
    layers=[
        keras.layers.InputLayer(input_shape=(28, 28), name="input"),
        keras.layers.Flatten(input_shape=(28, 28), name="flatten"),
        keras.layers.Dense(128, activation="relu", name="dense"),
        keras.layers.Dense(10, activation="softmax", name="output"),
    ],
    name="FCN",
)

# Compile model with optimizer
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

### Setting TensorFlow and Keras Models

After a model is created (trained or not), the graph of the model is
frozen and saved to file so the client method `client.set_model_from_file`
can load it into the database.

SmartSim includes a utility to freeze the graph of a TensorFlow or Keras model in
`smartsim.ml.tf`. To use TensorFlow or Keras in SmartSim, specify
`TF` as the argument for *backend* in the call to `client.set_model` or
`client.set_model_from_file`.

Note that TensorFlow and Keras, unlike the other ML libraries supported by
SmartSim, requires an `input` and `output` argument in the call to
`set_model`. These arguments correspond to the layer names of the
created model. The `smartsim.ml.tf.freeze_model` utility
returns these values for convenience as shown below.

In [12]:
from smartsim.ml.tf import freeze_model

# SmartSim utility for Freezing the model and saving it to a file.
model_path, inputs, outputs = freeze_model(model, os.getcwd(), "fcn.pb")

# use the same client we used for PyTorch to set the TensorFlow model
# this time the method for setting a model from a saved file is shown. 
# TensorFlow backed requires named inputs and outputs on graph
# this differs from PyTorch and ONNX.
client.set_model_from_file(
    "keras_fcn", model_path, "TF", device="CPU", inputs=inputs, outputs=outputs
)

# put random random input tensor into the database
input_data = np.random.rand(1, 28, 28).astype(np.float32)
client.put_tensor("input", input_data)

# run the Fully Connected Network model on the tensor we just put
# in and store the result of the inference at the "output" key
client.run_model("keras_fcn", "input", "output")

# get the result of the inference
pred = client.get_tensor("output")
print(pred)

[[0.10704935 0.16225594 0.30719754 0.02026123 0.15856391 0.03571513
  0.02464576 0.05195689 0.07600556 0.05634861]]


## Using ONNX

ONNX is a standard format for representing models. A number of different Machine Learning
Libraries are supported by ONNX and can be readily used with SmartSim.

Some popular ones are:


- [Scikit-learn](https://scikit-learn.org)
- [XGBoost](https://xgboost.readthedocs.io)
- [CatBoost](https://catboost.ai)
- [LightGBM](https://lightgbm.readthedocs.io/en/latest/)
- [libsvm](https://www.csie.ntu.edu.tw/~cjlin/libsvm/)


As well as some that are not listed. There are also many tools to help convert
models to ONNX.

- [onnxmltools](https://github.com/onnx/onnxmltools)
- [skl2onnx](https://github.com/onnx/sklearn-onnx/)
- [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx/)


And PyTorch has its own converter.

Currently the ONNX backend only works on Linux, but MacOS support will be added in the future.

Below are some examples of a few models in [Scikit-learn](https://scikit-learn.org)
that are converted into ONNX format for use with SmartSim. To use ONNX in SmartSim, specify
`ONNX` as the argument for *backend* in the call to `client.set_model` or
`client.set_model_from_file`

### Scikit-Learn K-means Cluster


K-means clustering is an unsupervised ML algorithm. It is used to categorize data points
into functional groups ("clusters"). Scikit Learn has a built in implementation of K-means clustering
and it is easily converted to ONNX for use with SmartSim through 
[skl2onnx.to_onnx](http://onnx.ai/sklearn-onnx/auto_examples/plot_convert_syntax.html)

Since the KMeans model returns two outputs, we provide the `client.run_model` call
with two `output` key names.


In [13]:
from skl2onnx import to_onnx
from sklearn.cluster import KMeans

In [14]:

X = np.arange(20, dtype=np.float32).reshape(10, 2)
tr = KMeans(n_clusters=2)
tr.fit(X)

# save the trained k-means model in memory with skl2onnx
kmeans = to_onnx(tr, X, target_opset=11)
model = kmeans.SerializeToString()

# random input data
sample = np.arange(20, dtype=np.float32).reshape(10, 2)

# use the same client from TensorFlow and Pytorch examples.
client.put_tensor("input", sample)
client.set_model("kmeans", model, "ONNX", device="CPU")
client.run_model("kmeans", inputs="input", outputs=["labels", "transform"])

print(client.get_tensor("labels"))


[0 0 0 0 0 1 1 1 1 1]


### Scikit-Learn Random Forest

The Random Forest example uses the Iris dataset from Scikit Learn to train a
RandomForestRegressor. As with the other examples, the skl2onnx function
`skl2onnx.to_onnx` is used to convert the model to ONNX format.


In [15]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [16]:
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, _ = train_test_split(X, y, random_state=13)
clr = RandomForestRegressor(n_jobs=1, n_estimators=100)
clr.fit(X_train, y_train)

rf_model = to_onnx(clr, X_test.astype(np.float32), target_opset=11)

sample = np.array([[6.4, 2.8, 5.6, 2.2]]).astype(np.float32)
model = rf_model.SerializeToString()

client.put_tensor("input", sample)
client.set_model("rf_regressor", model, "ONNX", device="CPU")
client.run_model("rf_regressor", inputs="input", outputs="output")
print(client.get_tensor("output"))


[[1.9999987]]


In [17]:
exp.stop(db)

14:12:27 C02G13RYMD6N SmartSim[96297] INFO Stopping model orchestrator_0 with job name orchestrator_0-CRU8GVZCMD2W


In [18]:
exp.summary(format="html")

'<table>\n<thead>\n<tr><th>  </th><th>Name          </th><th>Entity-Type  </th><th>JobID  </th><th>RunID  </th><th>Time    </th><th>Status   </th><th>Returncode  </th></tr>\n</thead>\n<tbody>\n<tr><td>0 </td><td>orchestrator_0</td><td>DBNode       </td><td>98890  </td><td>0      </td><td>132.3518</td><td>Cancelled</td><td>-9          </td></tr>\n</tbody>\n</table>'

# Colocated Deployment

A colocated Orchestrator is a special type of Orchestrator that is deployed
on the same compute hosts an a Model instance defined by the user. In this
deployment, the database is not connected together in a cluster and each shard
of the database is addressed individually by the processes running on that compute
host. This is particularly important for GPU-intensive workloads which require
frequent communication with the database.

<img src="https://www.craylabs.org/docs/_images/co-located-orc-diagram.png" alt="lattice" width="600"/>


In [19]:
# create colocated model
colo_settings = exp.create_run_settings(
    exe="python",
    exe_args="./colo-db-torch-example.py"
)

colo_model = exp.create_model("colocated_model", colo_settings)
colo_model.colocate_db_tcp(
    port=6780,
    db_cpus=1,
    limit_app_cpus=False,
    debug=False,
    ifname="lo"
)

In [20]:
exp.start(colo_model, summary=True)

14:13:01 C02G13RYMD6N SmartSim[96297] INFO 

=== Launch Summary ===
Experiment: Inference-Tutorial
Experiment Path: /Users/mrdro/repos/ssimdev/ss/tutorials/ml_inference/Inference-Tutorial
Launcher: local
Models: 1
Database Status: inactive

=== Models ===
colocated_model
Executable: /Users/mrdro/miniconda3/envs/smartsim/bin/python
Executable Arguments: ./colo-db-torch-example.py
Co-located Database: True



14:13:13 C02G13RYMD6N SmartSim[96297] INFO colocated_model(99077): Completed


In [21]:
exp.summary(format="html")

'<table>\n<thead>\n<tr><th>  </th><th>Name           </th><th>Entity-Type  </th><th>JobID  </th><th>RunID  </th><th>Time    </th><th>Status   </th><th>Returncode  </th></tr>\n</thead>\n<tbody>\n<tr><td>0 </td><td>orchestrator_0 </td><td>DBNode       </td><td>98890  </td><td>0      </td><td>132.3518</td><td>Cancelled</td><td>-9          </td></tr>\n<tr><td>1 </td><td>colocated_model</td><td>Model        </td><td>99077  </td><td>0      </td><td>2.0025  </td><td>Completed</td><td>0           </td></tr>\n</tbody>\n</table>'